apiVersion: v1
kind: Service
metadata:
  name: drug-detector-service
spec:
  ports:
  - port: 80
    targetPort: tf-serving-port
    protocol: TCP
  selector:
    app: drug-detector-gpu
  type: LoadBalancer
